/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.janskyd.lab2;

/**
 * A JPanel component that displays the exam welcome text before the user begins
 * the exam.
 * @author Ian Duncan
 */
public class ExamWelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new JPanel component that will be displayed to the user before
     * they begin the exam.
     * @param welcomeText The welcome text of the exam.
     */
    public ExamWelcomePanel(String welcomeText) {
        initComponents();
        
        /*
        JLabels do not support text wrapping when given plain text to display.
        They, do, however, support text wrapping when given HTML. We take
        advantage of this by wrapping our plain welcome text in a minimal HTML
        document.
        */
        this.welcomeTextLabel.setText("<html><body>" + welcomeText + "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTextLabel = new javax.swing.JLabel();

        welcomeTextLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        welcomeTextLabel.setText("jLabel1");
        welcomeTextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel welcomeTextLabel;
    // End of variables declaration//GEN-END:variables
}
