/*
 * Copyright 2019 Ian Duncan
 * For YSC3232 Software Engineering, 2019-20 Sem 1
 */
package com.janskyd.lab2;

/**
 *
 * @author Ian Duncan
 */
public class ExamFinishedPanel extends javax.swing.JPanel {

    /**
     * Creates a new JPanel displayed when the examination is finished.
     * @param finishedText The finishedText of the exam.
     */
    public ExamFinishedPanel(String finishedText) {
        initComponents();
        
        /*
        JLabels do not support text wrapping when given plain text to display.
        They, do, however, support text wrapping when given HTML. We take
        advantage of this by wrapping our plain welcome text in a minimal HTML
        document.
        */
        this.finishedTextLabel.setText("<html><body>" + finishedText + "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finishedTextLabel = new javax.swing.JLabel();

        finishedTextLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        finishedTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        finishedTextLabel.setText("Finished text");
        finishedTextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finishedTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finishedTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finishedTextLabel;
    // End of variables declaration//GEN-END:variables
}
