/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.janskyd.lab2;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author jansky
 */
public class ExtendedAnswerQuestionPanel extends javax.swing.JPanel {
    
    private ExtendedAnswerExamQuestion question;

    /**
     * Creates new form ExtendedAnswerQuestionPanel
     */
    public ExtendedAnswerQuestionPanel(ExtendedAnswerExamQuestion question) {
        
        this.question = question;
        
        initComponents();
        
        this.questionTextLabel.setText("<html><body>" + this.question.text() + "</body></html>");
        questionTextLabel.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        
        this.extendedAnswerText.getDocument().addDocumentListener(new DocumentListener() {
            
            private void updateText(DocumentEvent e) {
                Document doc = e.getDocument();
                
                
                try {
                    ExtendedAnswerQuestionPanel.this.question.setAnswer(doc.getText(0, doc.getLength()));
                } catch (BadLocationException ex) {
                    Logger.getLogger(ExtendedAnswerQuestionPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                
                updateText(e);

            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateText(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateText(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        extendedAnswerText = new javax.swing.JTextArea();
        questionTextLabel = new javax.swing.JLabel();

        jScrollPane3.setViewportView(jTextPane1);

        extendedAnswerText.setColumns(20);
        extendedAnswerText.setRows(5);
        extendedAnswerText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(extendedAnswerText);

        questionTextLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        questionTextLabel.setText("jLabel1");
        questionTextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(questionTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(questionTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea extendedAnswerText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel questionTextLabel;
    // End of variables declaration//GEN-END:variables
}
