/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

/**
 *
 * @author jansky
 */
public class ExamFinishedPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExamWelcomePanel
     */
    public ExamFinishedPanel(String finishedText) {
        initComponents();
        
        this.finishedTextLabel.setText("<html><body>" + finishedText + "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finishedTextLabel = new javax.swing.JLabel();

        finishedTextLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        finishedTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        finishedTextLabel.setText("Finished text");
        finishedTextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finishedTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finishedTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finishedTextLabel;
    // End of variables declaration//GEN-END:variables
}
